### ISSUE TITLE
Error: Dynamic Loading Error: build/src/libtdjson.so.1.8.6: cannot open shared object file: No such file or directory at new TDLib

### ISSUE THREAD

**Issue by 0xYYY** [Bannerets/tdl#124]
Trying to use `tdl` on Google Cloud Functions (serverless application platform). And I encountered this issue that when calling `TDLib(/PATH/TO/LIBTDJSON)`.

Code:
```javascript
import {
    Context,
    EventFunction,
} from '@google-cloud/functions-framework/build/src/functions';
import { PubsubMessage } from '@google-cloud/pubsub/build/src/publisher';

import { Client } from 'tdl';
import { TDLib } from 'tdl-tdlib-addon';

import * as fs from 'fs';

export const handlePubSub: EventFunction = (
    message: PubsubMessage,
    context: Context
) => {
    const appId = Number(process.env.TELEGRAM_APP_ID);
    const appHash = process.env.TELEGRAM_APP_HASH;

    const files = fs.readdirSync('./build/src');
    for (const file of files) {
        console.log(file);
    }

    fs.stat('./build/src/libtdjson.so.1.8.6', (err, stats) => {
        if (err) {
            console.log(err);
        } else {
            console.log(stats);
        }
    });

    const client = new Client(new TDLib('./build/src/libtdjson.so.1.8.6'), {
        apiId: appId,
        apiHash: appHash,
    });
};
```

Log:
```
Default 2022-10-07 01:14:35.063 index.d.ts
Default 2022-10-07 01:14:35.063 index.js
Default 2022-10-07 01:14:35.063 index.js.map
Default 2022-10-07 01:14:35.063 libtdjson.so.1.8.6

Default 2022-10-07 01:14:35.065 Stats {
Default 2022-10-07 01:14:35.065  dev: 27,
Default 2022-10-07 01:14:35.065  mode: 33261,
Default 2022-10-07 01:14:35.065  nlink: 1,
Default 2022-10-07 01:14:35.065  uid: 33,
Default 2022-10-07 01:14:35.065  gid: 33,
Default 2022-10-07 01:14:35.065  rdev: 0,
Default 2022-10-07 01:14:35.065  blksize: 4096,
Default 2022-10-07 01:14:35.065  ino: 583,
Default 2022-10-07 01:14:35.065  size: 37294432,
Default 2022-10-07 01:14:35.065  blocks: 72841,
Default 2022-10-07 01:14:35.066  atimeMs: 1665076034863.7378,
Default 2022-10-07 01:14:35.066  mtimeMs: 315532801000,
Default 2022-10-07 01:14:35.066  ctimeMs: 315532801000,
Default 2022-10-07 01:14:35.066  birthtimeMs: 0,
Default 2022-10-07 01:14:35.066  atime: 2022-10-06T17:07:14.864Z,
Default 2022-10-07 01:14:35.066  mtime: 1980-01-01T00:00:01.000Z,
Default 2022-10-07 01:14:35.066  ctime: 1980-01-01T00:00:01.000Z,
Default 2022-10-07 01:14:35.066  birthtime: 1970-01-01T00:00:00.000Z
Default 2022-10-07 01:14:35.066 }

Error 2022-10-07 01:14:36.067 Error: Dynamic Loading Error: ./build/src/libtdjson.so.1.8.6: cannot open shared object file: No such file or directory at new TDLib (/layers/google.nodejs.yarn/yarn_modules/node_modules/tdl-tdlib-addon/dist/index.js:39:17) at handlePubSub (/workspace/build/src/index.js:27:37) at /layers/google.nodejs.yarn/yarn_modules/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:144:25 at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Note that when listing files under `./build/src`, `libtdjson.so.1.8.6` is there and getting its stats also works. However, when trying to instantiate `TDLib` with `./build/src/libtdjson.so.1.8.6`, we encounter the error `Error: Dynamic Loading Error: ./build/src/libtdjson.so.1.8.6: cannot open shared object file: No such file or directory at new TDLib`.

What might be the cause of this inconsistent scenario here?

**Comment by Bannerets** [comment]
Hi! Try to execute `ldd ./build/src/libtdjson.so.1.8.6`, for example: `require('child_process').exec('ldd ./build/src/libtdjson.so.1.8.6',
(err, stdout, stderr) => console.log(err, stdout, stderr))`

**Comment by 0xYYY** [comment]
Thanks for the quick response and the suggestion. The output of that is
```
Error: Command failed: ldd libtdjson.so
at ChildProcess.exithandler (node:child_process:400:12)
at ChildProcess.emit (node:events:513:28)
at ChildProcess.emit (node:domain:552:15)
at maybeClose (node:internal/child_process:1093:16)
at Socket.<anonymous> (node:internal/child_process:451:11)
at Socket.emit (node:events:513:28)
at Socket.emit (node:domain:552:15)
at Pipe.<anonymous> (node:net:757:14)
at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
 code: 1,
 killed: false,
 signal: null,
 cmd: 'ldd libtdjson.so'
} not a dynamic executable
```
After seeing this message, I was able to identify and fix the issue. Documenting the details here for others' reference.


Google Cloud Functions [execution environment](https://cloud.google.com/functions/docs/concepts/execution-environment) for nodejs16 runtime is Ubuntu 18.04, but [`prebuilt-tdlib`](https://github.com/Bannerets/tdl/blob/master/packages/prebuilt-tdlib/README.md) is built against Ubuntu 20.04. So I spinned up a Ubuntu 18.04 docker to build `tdlib` myself. The problem is that I'm using an M2 Mac (Apple Silicon), so the object is actually built with `ARM aarch64` architecture.
 ```console
$ file libtdjson.so
libtdjson.so: ELF 64-bit LSB shared object, **ARM aarch64**, version 1 (SYSV), dynamically linked, not stripped
```

I ended up creating a repo and built the `tdlibjson.so` object with Github Workflow with steps borrowed from [here](https://github.com/Bannerets/tdl/blob/master/.github/workflows/prebuilt-tdlib.yml).
