### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/app/libtdjson.so'

### ISSUE THREAD

**Issue by adavidof** [Bannerets/tdl#21]
Locally it works.
But on server - not.

I have file on server:
`./app/libtdjson.dylib`

In the code I do this:
```js
client = new Client({
  apiId: api_id,
  apiHash: hash,
  loginDetails: {
    type: 'user',
    phoneNumber: '+xxxxxxxxxx'
  }
});
```

2018-08-29T03:28:34.971644+00:00 app[web.1]: Auth error { Error: ENOENT: no such file or directory, open '/app/libtdjson.so'
2018-08-29T03:28:34.971647+00:00 app[web.1]: at Object.openSync (fs.js:434:3)
2018-08-29T03:28:34.971649+00:00 app[web.1]: at readFileSync (fs.js:339:35)
2018-08-29T03:28:34.971660+00:00 app[web.1]: at new DynamicLibrary (/app/node_modules/ffi-napi/lib/dynamic_library.js:67:23)
2018-08-29T03:28:34.971662+00:00 app[web.1]: at Object.Library (/app/node_modules/ffi-napi/lib/library.js:45:14)
2018-08-29T03:28:34.971668+00:00 app[web.1]: at new TDLib (/app/node_modules/tdl/dist/TDLib.js:38:37)
2018-08-29T03:28:34.971669+00:00 app[web.1]: at new Client (/app/node_modules/tdl/dist/Client.js:165:50)
2018-08-29T03:28:34.971671+00:00 app[web.1]: at Object.<anonymous> (/app/dist/telegram/channel-history/tg-with-tdlib/tg.js:357:26)
2018-08-29T03:28:34.971673+00:00 app[web.1]: at step (/app/dist/telegram/channel-history/tg-with-tdlib/tg.js:32:23)
2018-08-29T03:28:34.971674+00:00 app[web.1]: at Object.next (/app/dist/telegram/channel-history/tg-with-tdlib/tg.js:13:53)
2018-08-29T03:28:34.971676+00:00 app[web.1]: at /app/dist/telegram/channel-history/tg-with-tdlib/tg.js:7:71
2018-08-29T03:28:34.971678+00:00 app[web.1]: at new Promise (<anonymous>)
2018-08-29T03:28:34.971679+00:00 app[web.1]: at __awaiter (/app/dist/telegram/channel-history/tg-with-tdlib/tg.js:3:12)
2018-08-29T03:28:34.971685+00:00 app[web.1]: at Object.exports.parseSignalsFromChannels2 (/app/dist/telegram/channel-history/tg-with-tdlib/tg.js:337:58)
2018-08-29T03:28:34.971687+00:00 app[web.1]: at /app/dist/index.js:137:26
2018-08-29T03:28:34.971689+00:00 app[web.1]: at step (/app/dist/index.js:32:23)
2018-08-29T03:28:34.971691+00:00 app[web.1]: at Object.next (/app/dist/index.js:13:53)
2018-08-29T03:28:34.971693+00:00 app[web.1]: at /app/dist/index.js:7:71
2018-08-29T03:28:34.971695+00:00 app[web.1]: at new Promise (<anonymous>)
2018-08-29T03:28:34.971696+00:00 app[web.1]: at __awaiter (/app/dist/index.js:3:12)
2018-08-29T03:28:34.971698+00:00 app[web.1]: at init (/app/dist/index.js:133:12)
2018-08-29T03:28:34.971699+00:00 app[web.1]: at Object.<anonymous> (/app/dist/index.js:176:1)
2018-08-29T03:28:34.971701+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:689:30)
2018-08-29T03:28:34.971703+00:00 app[web.1]: errno: -2,
2018-08-29T03:28:34.971704+00:00 app[web.1]: syscall: 'open',
2018-08-29T03:28:34.971706+00:00 app[web.1]: code: 'ENOENT',
2018-08-29T03:28:34.971708+00:00 app[web.1]: path: '/app/libtdjson.so' }

@Bannerets 
What I missed?

**Comment by Bannerets** [comment]
Is it Linux server?
`libtdjson.dylib` only for macOS.

**Comment by adavidof** [comment]
@Bannerets 
no, this is Heroku node server

what should I do?
please help :)

**Comment by Bannerets** [comment]
so It seems that heroku uses Linux
you should compile tdlib for linux

**Comment by adavidof** [comment]
I updated the stack to `heroku-18` stack and the problem was resolved.

https://devcenter.heroku.com/articles/stack-packages
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
